name: Build Dosbox-Staging DEB Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download pre-built binary
        run: |
          wget https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.82.2/dosbox-staging-linux-x86_64-v0.82.2.tar.xz
          mkdir dosbox-staging
          tar -xf dosbox-staging-linux-x86_64-v0.82.2.tar.xz -C dosbox-staging --strip-components=1

      - name: Create debian directory structure
        run: |
          mkdir -p debian/DEBIAN
          mkdir -p debian/usr/share/applications
          mkdir -p debian/usr/share/icons/hicolor/1024x1024/apps
          mkdir -p debian/usr/share/icons/hicolor/128x128/apps
          mkdir -p debian/usr/share/icons/hicolor/16x16/apps
          mkdir -p debian/usr/share/icons/hicolor/22x22/apps
          mkdir -p debian/usr/share/icons/hicolor/24x24/apps
          mkdir -p debian/usr/share/icons/hicolor/256x256/apps
          mkdir -p debian/usr/share/icons/hicolor/32x32/apps
          mkdir -p debian/usr/share/icons/hicolor/48x48/apps
          mkdir -p debian/usr/share/icons/hicolor/512x512/apps
          mkdir -p debian/usr/share/icons/hicolor/96x96/apps
          mkdir -p debian/usr/share/icons/hicolor/scalable/apps
          mkdir -p debian/usr/share/doc/dosbox-staging
          mkdir -p debian/usr/bin
          mkdir -p debian/usr/share/man/man1
          mkdir -p debian/usr/share/dosbox-staging
          mkdir -p debian/usr/local/share/dosbox-staging
          mkdir -p debian/usr/local/share/dosbox-staging/glshaders

          # Copy files according to contents.txt
          cp dosbox-staging.desktop debian/usr/share/applications/
          cp dosbox-staging/LICENSE debian/usr/share/doc/dosbox-staging/
          cp dosbox-staging/README debian/usr/share/doc/dosbox-staging/
          cp dosbox-staging/dosbox debian/usr/bin/
          cp dosbox-staging/man/dosbox.1 debian/usr/share/man/man1/
          cp -r dosbox-staging/resources debian/usr/share/dosbox-staging/
          cp -r dosbox-staging/resources/glshaders debian/usr/local/share/dosbox-staging/

          # Copy icons
          cp dosbox-staging/icons/hicolor/1024x1024/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/1024x1024/apps/
          cp dosbox-staging/icons/hicolor/128x128/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/128x128/apps/
          cp dosbox-staging/icons/hicolor/16x16/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/16x16/apps/
          cp dosbox-staging/icons/hicolor/22x22/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/22x22/apps/
          cp dosbox-staging/icons/hicolor/24x24/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/24x24/apps/
          cp dosbox-staging/icons/hicolor/256x256/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/256x256/apps/
          cp dosbox-staging/icons/hicolor/32x32/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/32x32/apps/
          cp dosbox-staging/icons/hicolor/48x48/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/48x48/apps/
          cp dosbox-staging/icons/hicolor/512x512/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/512x512/apps/
          cp dosbox-staging/icons/hicolor/96x96/apps/org.dosbox-staging.dosbox-staging.png debian/usr/share/icons/hicolor/96x96/apps/
          cp dosbox-staging/icons/hicolor/scalable/apps/org.dosbox-staging.dosbox-staging.svg debian/usr/share/icons/hicolor/scalable/apps/

      - name: Create control file
        run: |
          echo "Package: dosbox-staging" > debian/DEBIAN/control
          echo "Version: 0.82.2-1" >> debian/DEBIAN/control
          echo "Architecture: amd64" >> debian/DEBIAN/control
          echo "Maintainer: Tiago Almeida <tiagovdaa@gmail.com>" >> debian/DEBIAN/control
          echo "Description: DOSBox Staging is a modern DOS emulator." >> debian/DEBIAN/control
          echo "Section: games" >> debian/DEBIAN/control
          echo "Priority: optional" >> debian/DEBIAN/control

      - name: Build DEB package
        run: dpkg-deb --build debian dosbox-staging.deb

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dosbox-staging-deb-package
          path: dosbox-staging.deb
          retention-days: 7
