name: Build Dosbox-Staging DEB Package

on:
push:
branches:
- main
pull_request:
branches:
- main
workflow_dispatch:

jobs:
build-package:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      repository: dosbox-staging/dosbox-staging
      ref: main

  - name: Build Docker image
    id: build-docker-image
    run: docker build -t dosbox-staging-builder -f Dockerfile .
    working-directory: .

  - name: Run build script in Docker container
    id: run-build-script
    run: docker run --rm -v "$(pwd):/dosbox-staging-src" dosbox-staging-builder /build.sh

  - name: Upload .deb package as artifact
    uses: actions/upload-artifact@v4
    with:
      name: dosbox-staging-deb-package
      path: dosbox-staging.deb
      retention-days: 7
